/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FibRouteImport } from './routes/fib'
import { Route as FootprintRouteImport } from './routes/footprint'
import { Route as LiquidityRouteImport } from './routes/liquidity'
import { Route as OrderflowRouteImport } from './routes/orderflow'
import { Route as SpoofingRouteImport } from './routes/spoofing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FibRoute = FibRouteImport.update({
  id: '/fib',
  path: '/fib',
  getParentRoute: () => rootRouteImport,
} as any)
const FootprintRoute = FootprintRouteImport.update({
  id: '/footprint',
  path: '/footprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidityRoute = LiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderflowRoute = OrderflowRouteImport.update({
  id: '/orderflow',
  path: '/orderflow',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofingRoute = SpoofingRouteImport.update({
  id: '/spoofing',
  path: '/spoofing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fib': typeof FibRoute
  '/footprint': typeof FootprintRoute
  '/liquidity': typeof LiquidityRoute
  '/orderflow': typeof OrderflowRoute
  '/spoofing': typeof SpoofingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fib': typeof FibRoute
  '/footprint': typeof FootprintRoute
  '/liquidity': typeof LiquidityRoute
  '/orderflow': typeof OrderflowRoute
  '/spoofing': typeof SpoofingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fib': typeof FibRoute
  '/footprint': typeof FootprintRoute
  '/liquidity': typeof LiquidityRoute
  '/orderflow': typeof OrderflowRoute
  '/spoofing': typeof SpoofingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/fib' | '/footprint' | '/liquidity' | '/orderflow' | '/spoofing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fib' | '/footprint' | '/liquidity' | '/orderflow' | '/spoofing'
  id:
    | '__root__'
    | '/'
    | '/fib'
    | '/footprint'
    | '/liquidity'
    | '/orderflow'
    | '/spoofing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FibRoute: typeof FibRoute
  FootprintRoute: typeof FootprintRoute
  LiquidityRoute: typeof LiquidityRoute
  OrderflowRoute: typeof OrderflowRoute
  SpoofingRoute: typeof SpoofingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fib': {
      id: '/fib'
      path: '/fib'
      fullPath: '/fib'
      preLoaderRoute: typeof FibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footprint': {
      id: '/footprint'
      path: '/footprint'
      fullPath: '/footprint'
      preLoaderRoute: typeof FootprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidity': {
      id: '/liquidity'
      path: '/liquidity'
      fullPath: '/liquidity'
      preLoaderRoute: typeof LiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orderflow': {
      id: '/orderflow'
      path: '/orderflow'
      fullPath: '/orderflow'
      preLoaderRoute: typeof OrderflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoofing': {
      id: '/spoofing'
      path: '/spoofing'
      fullPath: '/spoofing'
      preLoaderRoute: typeof SpoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FibRoute: FibRoute,
  FootprintRoute: FootprintRoute,
  LiquidityRoute: LiquidityRoute,
  OrderflowRoute: OrderflowRoute,
  SpoofingRoute: SpoofingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
