/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FibRouteImport } from './routes/fib'
import { Route as FootprintRouteImport } from './routes/footprint'
import { Route as LiquidityRouteImport } from './routes/liquidity'
import { Route as LogRouteImport } from './routes/log'
import { Route as MathRouteImport } from './routes/math'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OrderflowRouteImport } from './routes/orderflow'
import { Route as ScalpingRouteImport } from './routes/scalping'
import { Route as SpoofingRouteImport } from './routes/spoofing'
import { Route as SwingRouteImport } from './routes/swing'
import { Route as UltimateRouteImport } from './routes/ultimate'
import { Route as WhaleRouteImport } from './routes/whale'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FibRoute = FibRouteImport.update({
  id: '/fib',
  path: '/fib',
  getParentRoute: () => rootRouteImport,
} as any)
const FootprintRoute = FootprintRouteImport.update({
  id: '/footprint',
  path: '/footprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidityRoute = LiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderflowRoute = OrderflowRouteImport.update({
  id: '/orderflow',
  path: '/orderflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ScalpingRoute = ScalpingRouteImport.update({
  id: '/scalping',
  path: '/scalping',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoofingRoute = SpoofingRouteImport.update({
  id: '/spoofing',
  path: '/spoofing',
  getParentRoute: () => rootRouteImport,
} as any)
const SwingRoute = SwingRouteImport.update({
  id: '/swing',
  path: '/swing',
  getParentRoute: () => rootRouteImport,
} as any)
const UltimateRoute = UltimateRouteImport.update({
  id: '/ultimate',
  path: '/ultimate',
  getParentRoute: () => rootRouteImport,
} as any)
const WhaleRoute = WhaleRouteImport.update({
  id: '/whale',
  path: '/whale',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fib': typeof FibRoute
  '/footprint': typeof FootprintRoute
  '/liquidity': typeof LiquidityRoute
  '/log': typeof LogRoute
  '/math': typeof MathRoute
  '/news': typeof NewsRoute
  '/orderflow': typeof OrderflowRoute
  '/scalping': typeof ScalpingRoute
  '/spoofing': typeof SpoofingRoute
  '/swing': typeof SwingRoute
  '/ultimate': typeof UltimateRoute
  '/whale': typeof WhaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fib': typeof FibRoute
  '/footprint': typeof FootprintRoute
  '/liquidity': typeof LiquidityRoute
  '/log': typeof LogRoute
  '/math': typeof MathRoute
  '/news': typeof NewsRoute
  '/orderflow': typeof OrderflowRoute
  '/scalping': typeof ScalpingRoute
  '/spoofing': typeof SpoofingRoute
  '/swing': typeof SwingRoute
  '/ultimate': typeof UltimateRoute
  '/whale': typeof WhaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fib': typeof FibRoute
  '/footprint': typeof FootprintRoute
  '/liquidity': typeof LiquidityRoute
  '/log': typeof LogRoute
  '/math': typeof MathRoute
  '/news': typeof NewsRoute
  '/orderflow': typeof OrderflowRoute
  '/scalping': typeof ScalpingRoute
  '/spoofing': typeof SpoofingRoute
  '/swing': typeof SwingRoute
  '/ultimate': typeof UltimateRoute
  '/whale': typeof WhaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fib'
    | '/footprint'
    | '/liquidity'
    | '/log'
    | '/math'
    | '/news'
    | '/orderflow'
    | '/scalping'
    | '/spoofing'
    | '/swing'
    | '/ultimate'
    | '/whale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fib'
    | '/footprint'
    | '/liquidity'
    | '/log'
    | '/math'
    | '/news'
    | '/orderflow'
    | '/scalping'
    | '/spoofing'
    | '/swing'
    | '/ultimate'
    | '/whale'
  id:
    | '__root__'
    | '/'
    | '/fib'
    | '/footprint'
    | '/liquidity'
    | '/log'
    | '/math'
    | '/news'
    | '/orderflow'
    | '/scalping'
    | '/spoofing'
    | '/swing'
    | '/ultimate'
    | '/whale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FibRoute: typeof FibRoute
  FootprintRoute: typeof FootprintRoute
  LiquidityRoute: typeof LiquidityRoute
  LogRoute: typeof LogRoute
  MathRoute: typeof MathRoute
  NewsRoute: typeof NewsRoute
  OrderflowRoute: typeof OrderflowRoute
  ScalpingRoute: typeof ScalpingRoute
  SpoofingRoute: typeof SpoofingRoute
  SwingRoute: typeof SwingRoute
  UltimateRoute: typeof UltimateRoute
  WhaleRoute: typeof WhaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fib': {
      id: '/fib'
      path: '/fib'
      fullPath: '/fib'
      preLoaderRoute: typeof FibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footprint': {
      id: '/footprint'
      path: '/footprint'
      fullPath: '/footprint'
      preLoaderRoute: typeof FootprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidity': {
      id: '/liquidity'
      path: '/liquidity'
      fullPath: '/liquidity'
      preLoaderRoute: typeof LiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orderflow': {
      id: '/orderflow'
      path: '/orderflow'
      fullPath: '/orderflow'
      preLoaderRoute: typeof OrderflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scalping': {
      id: '/scalping'
      path: '/scalping'
      fullPath: '/scalping'
      preLoaderRoute: typeof ScalpingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoofing': {
      id: '/spoofing'
      path: '/spoofing'
      fullPath: '/spoofing'
      preLoaderRoute: typeof SpoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swing': {
      id: '/swing'
      path: '/swing'
      fullPath: '/swing'
      preLoaderRoute: typeof SwingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ultimate': {
      id: '/ultimate'
      path: '/ultimate'
      fullPath: '/ultimate'
      preLoaderRoute: typeof UltimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whale': {
      id: '/whale'
      path: '/whale'
      fullPath: '/whale'
      preLoaderRoute: typeof WhaleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FibRoute: FibRoute,
  FootprintRoute: FootprintRoute,
  LiquidityRoute: LiquidityRoute,
  LogRoute: LogRoute,
  MathRoute: MathRoute,
  NewsRoute: NewsRoute,
  OrderflowRoute: OrderflowRoute,
  ScalpingRoute: ScalpingRoute,
  SpoofingRoute: SpoofingRoute,
  SwingRoute: SwingRoute,
  UltimateRoute: UltimateRoute,
  WhaleRoute: WhaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
